const sampleListings = [
  {
    title: "Cozy Beachfront Cottage",
    description: "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and peaceful vibes.",
    image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b",
    price: 1500,
    location: "Malibu",
    country: "United States",
  },
  {
    title: "Modern Loft in Downtown",
    description: "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers.",
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
    price: 1200,
    location: "New York City",
    country: "United States",
  },
  {
    title: "Rustic Mountain Cabin",
    description: "A cozy cabin in the mountains surrounded by pine trees. Great for hiking and relaxation.",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    price: 800,
    location: "Aspen",
    country: "United States",
  },
  {
    title: "Luxury Villa with Pool",
    description: "A spacious villa featuring a private pool, perfect for families or groups.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    price: 3000,
    location: "Bali",
    country: "Indonesia",
  },
  {
    title: "Charming Paris Apartment",
    description: "Experience Paris from this charming apartment with Eiffel Tower views.",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
    price: 1800,
    location: "Paris",
    country: "France",
  },
  {
    title: "Countryside Farmhouse",
    description: "A traditional farmhouse surrounded by fields. Great for a quiet escape.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
    price: 950,
    location: "Tuscany",
    country: "Italy",
  },
  {
    title: "Lakeview Cabin",
    description: "Enjoy serene mornings with lake views from this wooden cabin.",
    image: "https://images.unsplash.com/photo-1505691723518-36a5ac3be353",
    price: 1000,
    location: "Lake Tahoe",
    country: "United States",
  },
  {
    title: "Desert Retreat",
    description: "Unique desert experience with modern comforts and starry skies.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    price: 1100,
    location: "Joshua Tree",
    country: "United States",
  },
  {
    title: "Tokyo City Apartment",
    description: "Compact and modern apartment in Shinjuku, perfect for business travelers.",
    image: "https://images.unsplash.com/photo-1528909514045-2fa4ac7a08ba",
    price: 1400,
    location: "Tokyo",
    country: "Japan",
  },
  {
    title: "Beach Hut Escape",
    description: "Colorful beach hut right on the sand. Perfect for sun lovers.",
    image: "https://images.unsplash.com/photo-1470240731273-7821a6eeb6bd",
    price: 600,
    location: "Goa",
    country: "India",
  },
  {
    title: "Santorini White Villa",
    description: "Iconic whitewashed villa with breathtaking sea views.",
    image: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29",
    price: 2000,
    location: "Santorini",
    country: "Greece",
  },
  {
    title: "Countryside Cottage",
    description: "A little stone cottage surrounded by gardens and nature.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
    price: 750,
    location: "Cornwall",
    country: "United Kingdom",
  },
  {
    title: "Luxury Dubai Penthouse",
    description: "High-rise penthouse with skyline views and premium amenities.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    price: 5000,
    location: "Dubai",
    country: "UAE",
  },
  {
    title: "Ski Chalet",
    description: "Cozy ski chalet with fireplace, great for winter sports lovers.",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
    price: 2200,
    location: "Swiss Alps",
    country: "Switzerland",
  },
  {
    title: "Hawaiian Beach House",
    description: "Tropical beach house steps away from the ocean.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    price: 2500,
    location: "Maui",
    country: "United States",
  },
  {
    title: "Treehouse Retreat",
    description: "Live among the treetops in this unique treehouse stay.",
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e",
    price: 900,
    location: "Costa Rica",
    country: "Costa Rica",
  },
  {
    title: "Modern Studio Apartment",
    description: "Compact studio perfect for solo travelers or couples.",
    image: "https://images.unsplash.com/photo-1554995207-c18c203602cb",
    price: 700,
    location: "Berlin",
    country: "Germany",
  },
  {
    title: "Secluded Island Villa",
    description: "Private island villa with crystal clear waters all around.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    price: 4500,
    location: "Maldives",
    country: "Maldives",
  },
  {
    title: "Urban Chic Condo",
    description: "Trendy condo located near the best restaurants and nightlife.",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    price: 1300,
    location: "Toronto",
    country: "Canada",
  },
  {
    title: "Safari Lodge",
    description: "Stay close to nature in this safari lodge with guided tours.",
    image: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29",
    price: 1700,
    location: "Nairobi",
    country: "Kenya",
  },
  {
    title: "Historic Castle Stay",
    description: "Live like royalty in this renovated medieval castle.",
    image: "https://images.unsplash.com/photo-1464146072230-91cabc968266",
    price: 4000,
    location: "Edinburgh",
    country: "Scotland",
  },
  {
    title: "Tropical Jungle Villa",
    description: "Villa surrounded by lush jungle, complete with infinity pool.",
    image: "https://images.unsplash.com/photo-1505691723518-36a5ac3be353",
    price: 2300,
    location: "Ubud",
    country: "Indonesia",
  },
  {
    title: "Countryside Barn",
    description: "A rustic converted barn for a peaceful countryside experience.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
    price: 850,
    location: "Devon",
    country: "United Kingdom",
  },
  {
    title: "Icelandic Cabin",
    description: "Wooden cabin surrounded by glaciers and hot springs.",
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
    price: 1600,
    location: "Reykjavik",
    country: "Iceland",
  },
  {
    title: "Sydney Harbor Apartment",
    description: "Modern apartment with stunning views of the Sydney Opera House.",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
    price: 1900,
    location: "Sydney",
    country: "Australia",
  }
];

module.exports = {data: sampleListings};